version: '3'
services:
  app:
    image: infracloudio/csvserver:latest
    restart: always
    read_only: true
    environment:
    - CSVSERVER_BORDER=Orange
    ports: 
    - "9393:9300"
    volumes:
    - ./inputFile:/csvserver/inputdata

  prometheus:
    image: prom/prometheus:v2.22.0
    ports:
    - "9090:9090"
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
